[package]
name = "angsd-io"
version = "0.1.0"
authors = ["Malthe Sebro Rasmussen <malthe.rasmussen@bio.ku.dk>"]
edition = "2018"

[features]
default = ["ndarray"]

[dependencies]
byteorder = "1.4.*"
flate2 = "1.0.*"

ndarray = { version = "0.14.*", optional = true }
